### ISSUE TITLE
버튼, 라벨 컴포넌트 스타일 수정 및 홈 리뷰 카드 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by suubiin** [FRONTENDSCHOOL10/Pisa-s-4top#100]
## 📄 설명

버튼, 라벨 컴포넌트 스타일 수정 및 홈 리뷰 카드 컴포넌트 리팩토링

## 📋 TO-DO

- [ ] 버튼 컴포넌트 스타일 수정
- [ ] 라벨 컴포넌트 스타일 수정
- [ ] 홈 리뷰 카드 컴포넌트 리팩토링
