### ISSUE TITLE
App Bar 컴포넌트 작업

### ISSUE THREAD

**Issue by minnje** [FRONTENDSCHOOL10/Pisa-s-4top#13]
## 📄 설명

App Bar (상단) 컴포넌트 작업

## 📋 TO-DO

- [x] App Bar 컴포넌트 마크업
- [x] App Bar 컴포넌트 스타일링
- [x] App Bar 컴포넌트 기능

## 🔔 기타
