### ISSUE TITLE
Logo 컴포넌트 작업

### ISSUE THREAD

**Issue by minnje** [FRONTENDSCHOOL10/Pisa-s-4top#17]
## 📄 설명

로고 컴포넌트 작업

## 📋 TO-DO

- [x] Logo 컴포넌트 마크업
- [x] Logo 컴포넌트 스타일링
- [x] Logo 컴포넌트 기능
