### ISSUE TITLE
fetchData 반영 수정 필요 페이지

### ISSUE THREAD

**Issue by suubiin** [FRONTENDSCHOOL10/Pisa-s-4top#296]
## 📋 TO-DO

- [x] 추천 티 리스트 페이지
- [x] 티 리뷰 리스트 카테고리 탭 버튼
- [x] 티 리뷰 상세 페이지
- [x] 나의 찜 페이지
- [x] 나의 리뷰 페이지 탭 버튼
