### ISSUE TITLE
검색/마이페이지 수정/당신의 취향 스플래시 페이지 코드 리팩터링

### ISSUE THREAD

**Issue by happyhye** [FRONTENDSCHOOL10/Pisa-s-4top#347]
## 📋 TO-DO

- [ ] 검색 페이지 리팩터링
- [ ] 마이페이지 수정 리팩터링
- [ ] 당신의 취향 스플래시 페이지 리팩터링
- [ ] 폰트 굵은 거 → 전부 bold로
