### ISSUE TITLE
패키지 설치/제거

### ISSUE THREAD

**Issue by happyhye** [FRONTENDSCHOOL10/Pisa-s-4top#38]
## 📄 설명

패키지 설치/제거

## 📋 TO-DO

- [x] 접근성 검사 라이브러리 설치
- [x] cox-postposition 패키지 설치
- [x] prop-types 패키지 제거
