### ISSUE TITLE
2차 마일스톤 반영하면 좋을 것들 정리

### ISSUE THREAD

**Issue by woolen-h** [FRONTENDSCHOOL10/Pisa-s-4top#381]
## 📄 설명

발표 이후 개발 사항에 대해 정리 - 디자이너들에게 QA를 시켜보았어요

## 📋 TO-DO

- [ ] 티 검색 시 과거 검색 결과 뜨게 하기
- [x] 비밀번호 확인란 placeholder 수정 '비밀번호를 다시 입력해주세요'
- [x] 비밀번호 입력란 하단 에러 메시지 320px에서 인풋란 침범
- [x] 회원가입 input 라벨 추가
- [x] 비밀번호 보이게 하는 기능 추가
- [ ] 320px에서 로고 잘리는 현상
